services:
  - type: web
    name: ticket-system
    env: python
    plan: free
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: DISCORD_WEBHOOK_URL
        value: https://discord.com/api/webhooks/1401481441673740331/38Ij4PE0Ce0__gknAIgXSu7TOWfM34B-p5eU9v162CyIqyX6jR8YWH9NcmHSiK_kX-F_
